FROM node:22-bookworm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

COPY prisma ./prisma

RUN corepack enable

RUN pnpm install

RUN pnpm prisma:generate

RUN pnpm approve-builds -a && pnpm rebuild

EXPOSE 3000

CMD ["pnpm", "dev"]